version: '3.8'

services:
  tmcshinyproxy:
    build: 
      context: .
      dockerfile: Dockerfile
    image: tmcshinyproxy:latest
    networks:
      - tmcshinyproxy_network
    ports:
      - "8082:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

networks:
  tmcshinyproxy_network:
    driver: bridge